### ISSUE TITLE
Hunging in case of uploader failure

### ISSUE THREAD

**Issue by PavelAndrianov** [ispras/cv#28]
If uploader cannot establish connection to server (for example, missed `openvpn`), it hungs:

```
Launcher: DEBUG: Processing results
Launcher: INFO: Preparing report on launches into file: '/home/alpha/git/cv/results/report_launches_sync_develop_2023_04_26_09_54_41.csv'
Launcher: INFO: Preparing report on components into file: '/home/alpha/git/cv/results/report_components_sync_develop_2023_04_26_09_54_41.csv'
Launcher: INFO: Preparing short report into file: '/home/alpha/git/cv/results/short_report_sync_develop_2023_04_26_09_54_41.csv'
Launcher: INFO: Exporting results into archive: '/home/alpha/git/cv/results/results_sync_develop_2023_04_26_09_54_41.zip'
Exporter: DEBUG: Wall time: 1.03s
Exporter: DEBUG: CPU time: 1008.6s
Exporter: DEBUG: Memory usage: 7322Mb
Exporter: INFO: Exporting results has been completed
Launcher: INFO: Uploading results into server 10.10.2.179:8989 with identifier 2
Launcher: DEBUG: Using name 'sync:races 2023_04_26_09_54_43' for uploaded report

```
And nothing changes after 30 minutes. Even I connect to openvpn.

After interruption I get waiting stack:
```
Traceback (most recent call last):
  File "/home/alpha/git/cv/scripts/components/launcher.py", line 268, in _upload_results
    subprocess.check_call(command, shell=True)
  File "/usr/lib/python3.10/subprocess.py", line 364, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 347, in call
    return p.wait(timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1207, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1941, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.10/subprocess.py", line 1899, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
```

**Comment by vmordan** [comment]
Moved to https://github.com/ispras/cv-visualizer/issues/3
